name: Deploy Gui

on:
  workflow_dispatch:

jobs:
  build-gui:
    name: Build the executable files for mac and windows systems
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./gui
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Print Dir
        run: dir

      - name: Pyinstaller action
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.12.8"
          requirements: "gui/requirements.txt"
          spec: "gui/main.py"
          upload_exe_with_name: "ef-agent"
          exe_path: ./gui
          options: --onefile, --windowed, --name "ef-agent", --add-data "gui/images;images"

      - name: Check where exe created debug
        run: |
          echo Listing dir
          dir
          echo finding any exe that exists
          dir -s "*.exe"

      - name: Zip the exe file
        run: |
          Compress-Archive -Path "ef-agent.exe" -DestinationPath "ef-agnet.zip"

      - name: Debug after zip
        run: |
          echo Listing dir
          dir
          echo Looking for zip
          dir -s "*.zip"

      - name: Email new executable to admin
        uses: dawidd6/action-send-mail@v7
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{secrets.ADMIN_EMAIL}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: Exe File Is Ready For Download
          to: ${{secrets.ADMIN_EMAIL}}
          from: ${{secrets.ADMIN_EMAIL}}
          attachments: gui/ef-agent.zip
