name: Deploy Gui

on:
  workflow_dispatch:

jobs:
  build-gui:
    name: Build the executable files for mac and windows systems
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./gui
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Print Dir
        run: dir

      - name: Pyinstaller action
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.12.8"
          requirements: "gui/requirements.txt"
          spec: "gui/main.py"
          upload_exe_with_name: "ef-agent"
          exe_path: ./gui
          options: --onefile, --windowed, --add-data "gui/images;images"

      - name: Check where exe created debug
        run: |
          echo Listing dir
          dir
          echo finding any exe that exists
          find . -name '*.exe'
      - name: Email new executable to admin
        uses: dawidd6/action-send-mail@v7
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          subject: Exe File Is Ready For Download
          to: ${{secrets.ADMIN_EMAIL}}
          attachments: gui/dist/ef-agent.exe
