name: Deploy processes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build docker image and post to docker hub + launch on Ec2 instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Login To DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}

      - name: Build Docker Image
        id: build-docker-image
        run: docker buildx build -t ${{secrets.DOCKERHUB_USERNAME}}/product-agent:latest --platform linux/amd64 --push .

      - name: Create Pem File For SSH
        id: create-pem
        run: echo "${{secrets.PEM_FILE}}" > ty.pem

      - name: Give Permissions
        id: give-permissions
        run: chmod 0400 ty.pem

      - name: SSH In
        id: ssh-in
        run: ssh -o StrictHostKeyChecking=no -i ty.pem ec2-user@${{secrets.PUBLIC_IP}} "cd downloads && docker stop \$(docker ps -a -q) && docker rm \$(docker ps -a -q) && docker pull ${{secrets.DOCKERHUB_USERNAME}}/product-agent:latest && docker run -d -p ${{secrets.PORT_NUMBER}}:${{secrets.PORT_NUMBER}} --env-file .env ${{secrets.DOCKERHUB_USERNAME}}/product-agent:latest"

  build-gui:
    name: Build the executable files for mac and windows systems
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./gui
    steps:
      - name: Pyinstaller action
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.12.8"
          requirements: "requirements.txt"
          spec: "main.py"
          upload_exe_with_name: "ef-agent"
          options: --onefile, --windowed, --add-data "images:images"

      - name: Email new executable to admin
        uses: dawidd6/action-send-mail@v7
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          subject: Exe File Is Ready For Download
          to: ${{secrets.ADMIN_EMAIL}}
          attachments: ./dist/ef-agent.exe
