name: Deploy Gui

on:
  workflow_dispatch:

jobs:
  build-gui-windows:
    name: Build the executable files for mac and windows systems
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./gui
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Print Dir
        run: dir

      - name: Pyinstaller action
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.12.8"
          requirements: "gui/requirements.txt"
          spec: "gui/main.py"
          upload_exe_with_name: "ef-agent"
          exe_path: ./gui
          options: --onefile, --windowed, --name "ef-agent", --add-data "./gui/images;images", --add-data "./gui/.env;."

      - name: Check where exe created debug
        run: |
          echo Listing dir
          dir
          echo finding any exe that exists
          dir -s "*.exe"

      - name: Zip the exe file
        run: |
          Compress-Archive -Path "ef-agent.exe" -DestinationPath "ef-agent.zip"

      - name: Debug after zip
        run: |
          echo Listing dir
          dir
          echo Looking for zip
          dir -s "*.zip"

      - name: Create Env file for python script
        run: |
          echo DROPBOX_ACCESS_TOKEN=${{secrets.DROPBOX_ACCESS_TOKEN}} &&  > .env
          echo DROPBOX_APP_KEY=${{secrets.DROPBOOX_ACCESS_KEY}} >> .env
          echo DROPBOX_APP_SECRET=${{secrets.DROPBOOX_ACCESS_SECRET}} >> .env
          echo DROPBOX_REFRESH_TOKEN=${{secrets.DROPBOX_REFRESH_TOKEN}} >> .env
          echo API_BASE_URL=${{secrets.API_BASE_URL}} >> .env
          echo Print Dir for debug
          dir /A

      - name: Run python script
        run: |
          python upload_to_dropbox.py

  build-gui-mac:
    name: Build the executable on mac
    runs-on: macos-latest

    defaults:
      run:
        working-directory: ./gui

    steps:
      - name: Inspect repo
        uses: actions/checkout@v4

      - name: Print cwd
        run: |
          ls

      - name: Build env file for drop box script
        run: |
          echo DROPBOX_ACCESS_TOKEN=${{secrets.DROPBOX_ACCESS_TOKEN}} > .env
          echo DROPBOX_APP_KEY=${{secrets.DROPBOOX_ACCESS_KEY}} >> .env
          echo DROPBOX_APP_SECRET=${{secrets.DROPBOOX_ACCESS_SECRET}} >> .env
          echo DROPBOX_REFRESH_TOKEN=${{secrets.DROPBOX_REFRESH_TOKEN}} >> .env
          echo API_BASE_URL=${{secrets.API_BASE_URL}} >> .env
          echo Check Director for debugging
          ls -a
          echo Env File
          cat .env

      - name: Create mac executable
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: "./gui/main.py"
          requirements: "./gui/requirements.txt"
          python_ver: "3.12.8"
          exe_path: ./gui
          options: --onefile, --windowed, --name "ef-agent", --add-data "./gui/images:images", --add-data "./gui/.env:."

      - name: Check directory has a .app file
        run: |
          echo Printing Debug Directory
          ls
          echo Find a .app file
          find . -name "*.app"

      - name: Zip the executable
        run: |
          echo Print the cwd
          pwd
          echo Zip the executable
          zip -r ef-agent.zip ef-agent.app
          echo Print the dir to check its there
          ls

      - name: Run drop box script
        run: |
          python upload_to_dropbox.py

      - name: Email Admin
        uses: dawidd6/action-send-mail@v7
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{secrets.ADMIN_EMAIL}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: Exe File Is Ready For Download
          to: ${{secrets.ADMIN_EMAIL}}
          from: ${{secrets.ADMIN_EMAIL}}
          body: "New executables launched to drop box"
