name: Run Unit Tests

on: ["push"]

jobs:
  build:
    runs-on: ubunutu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: 3.12.3
          cache: "pip"

      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: pytest -m "not integration" --collect-only
